# Generated by Django 5.1 on 2025-01-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserServices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_verify",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
