# Generated by Django 5.1 on 2025-02-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserServices", "0002_users_is_verify"),
    ]

    operations = [
        migrations.AddField(
            model_name="modules",
            name="module_icon",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="modules",
            name="module_description",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="modules",
            name="module_url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Admin", "Admin"),
                    ("User", "User"),
                    ("Customer", "Customer"),
                    ("Staff", "Staff"),
                    ("Manager", "Manager"),
                    ("Super Admin", "Super Admin"),
                ],
                default="Admin",
                max_length=50,
                null=True,
            ),
        ),
    ]
